
const GLOBAL_TYPES = {
    LOGIN: 'LOGIN',
    NOTIFY: 'NOTIFY',
    THEME: 'THEME',
    STATUS: 'STATUS',
    CREATE_POST: 'CREATE_POST',
    GET_POSTS: 'GET_POSTS',
    UPDATE_POST: 'UPDATE_POST',
    RESET_POSTS: 'RESET_POSTS',
    UPDATE_POST_INORDER: 'UPDATE_POST_INORDER',
    UPDATE_POST_DETAIL: 'UPDATE_POST_DETAIL',
    LOAD_SUGGESTIONS: 'LOAD_SUGGESTIONS',
    SUGGESTIONS: 'SUGGESTIONS',
    SOCKET: 'SOCKET'
}

export default GLOBAL_TYPES;