
const GLOBAL_TYPES = {
    LOGIN: 'LOGIN',
    NOTIFY: 'NOTIFY',
    THEME: 'THEME',
    STATUS: 'STATUS',
    CREATE_POST: 'CREATE_POST',
    GET_POSTS: 'GET_POSTS',
    UPDATE_POST: 'UPDATE_POST',
    RESET_POSTS: 'RESET_POSTS',
    UPDATE_POST_INORDER: 'UPDATE_POST_INORDER',
    UPDATE_POST_DETAIL: 'UPDATE_POST_DETAIL',
    LOAD_SUGGESTIONS: 'LOAD_SUGGESTIONS',
    SUGGESTIONS: 'SUGGESTIONS',
    SOCKET: 'SOCKET',
    GET_NOTICES: 'GET_NOTICES',
    CREATE_NOTICE: 'CREATE_NOTICE',
    UPDATE_SOUND: 'UPDATE_SOUND',
    ADD_USER: 'ADD_USER',
    ADD_MESSAGE: 'ADD_MESSAGE',
    GET_CONVERSATIONS: 'GET_CONVERSATIONS',
    GET_MESSAGES: 'GET_MESSAGES',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    RESET_MESSENGER: 'RESET_MESSENGER',
    ONLINE: 'ONLINE',
    OFFLINE: 'OFFLINE'
}

export default GLOBAL_TYPES;