
const GLOBAL_TYPES = {
    LOGIN: 'LOGIN',
    NOTIFY: 'NOTIFY',
    THEME: 'THEME',
    STATUS: 'STATUS',
    CREATE_POST: 'CREATE_POST',
    GET_POSTS: 'GET_POSTS',
    UPDATE_POST: 'UPDATE_POST',
    RESET_POSTS: 'RESET_POSTS',
    UPDATE_POST_INORDER: 'UPDATE_POST_INORDER'
}

export default GLOBAL_TYPES;